### ISSUE TITLE
Problem with chrome and edge workflows

### ISSUE THREAD

**Issue by wdzeng** [Daniel-Mendes/import-wishlist#2]
Hi,

Thanks for using my workflows. I noticed there are some errors in the [chrome](https://github.com/Daniel-Mendes/import-wishlist/blob/8ab7ef1127dbc3d5bffabef071e2d5d36020e71d/.github/workflows/chrome-publish.yml) and [edge](https://github.com/Daniel-Mendes/import-wishlist/blob/8ab7ef1127dbc3d5bffabef071e2d5d36020e71d/.github/workflows/edge-publish.yml) workflows.

The chrome workflow should be:

```yml
name: Upload Chrome extension

on: [workflow_dispatch]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/chrome-extension@v1
        with:
          extension-id: jenjpehgcedkjfjmelkodhagcogpbmgl
          zip-path: build/extension.zip
          tester-only: false
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
```

where `jenjpehgcedkjfjmelkodhagcogpbmgl` is the extension id obtained from your extension on [Chrome Web Store URL](https://chrome.google.com/webstore/detail/import-wishlist/jenjpehgcedkjfjmelkodhagcogpbmgl). 

The edge workflow should be:

```yml
name: Upload Edge Add-on

on: [workflow_dispatch]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: wdzeng/edge-addon@v1
      with:
        product-id: fpjkbmpnfckpnaiijocjdfcjddnkjhnb
        zip-path: build/extension.zip
        client-id: ${{ secrets.EDGE_CLIENT_ID }}
        client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.EDGE_REFRESH_TOKEN_URL }}
```

where `fpjkbmpnfckpnaiijocjdfcjddnkjhnb` is obtained from your addon on [Microsoft Edge Addon URL](https://microsoftedge.microsoft.com/addons/detail/import-wishlist/fpjkbmpnfckpnaiijocjdfcjddnkjhnb).

Additionally, I noticed you are using my firefox workflow as well, while your project does not meet the requirement to be uploaded to Firefox Add-ons. An addon GUID is missing.
